trigger:
- main

stages:
# ===== CI: Build & publish artifact =====
- stage: Build
  displayName: Build
  jobs:
  - job: BuildJob
    pool: { name: Default }
    variables:
      solution: '**/*.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'
    steps:
    - task: NuGetToolInstaller@1
    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        msbuildArgs: >-
          /p:DeployOnBuild=true
          /p:WebPublishMethod=Package
          /p:PackageAsSingleFile=true
          /p:SkipInvalidConfigurations=true
          /p:DesktopBuildPackageLocation="$(Build.ArtifactStagingDirectory)\WebApp.zip"
          /p:DeployIisAppPath="Default Web Site"
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: VSTest@2
      inputs:
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - publish: '$(Build.ArtifactStagingDirectory)'
      artifact: drop

# ===== CD: SIT =====
- stage: Deploy_SIT
  displayName: Deploy to SIT
  dependsOn: Build
  jobs:
  - deployment: DeployToSIT
    environment: 'SIT'
    pool: { name: Default }
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
          - template: deploy-iis-steps.yml
            parameters:
              siteName:  'sit.dceg.co.za'
              appPool:   'sit.dceg.co.za'
              host:      'sit.dceg.co.za'
              physicalPath: 'C:\Sites\sit.dceg.co.za'

# ===== Approve UAT =====
- stage: Approve_UAT
  displayName: "Approve UAT"
  dependsOn: Deploy_SIT
  jobs:
  - job: WaitForApproval_UAT
    pool: server
    steps:
    - task: ManualValidation@0
      inputs:
        instructions: 'Approve deploy to UAT'
        notifyUsers: 'anton@dceg.co.za'
        onTimeout: 'reject'
      timeoutInMinutes: 1440

# ===== CD: UAT =====
- stage: Deploy_UAT
  displayName: Deploy to UAT
  dependsOn: Approve_UAT
  condition: succeeded()
  jobs:
  - deployment: DeployToUAT
    environment: 'UAT'
    pool: { name: Default }
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
          - template: deploy-iis-steps.yml
            parameters:
              siteName:  'uat.dceg.co.za'
              appPool:   'uat.dceg.co.za'
              host:      'uat.dceg.co.za'
              physicalPath: 'C:\Sites\uat.dceg.co.za'

# ===== Approve Prod =====
- stage: Approve_Prod
  displayName: "Approve Prod"
  dependsOn: Deploy_UAT
  jobs:
  - job: WaitForApproval_Prod
    pool: server
    steps:
    - task: ManualValidation@0
      inputs:
        instructions: 'Approve deploy to Prod'
        notifyUsers: 'anton@dceg.co.za'
        onTimeout: 'reject'
      timeoutInMinutes: 1440

# ===== CD: Prod =====
- stage: Deploy_Prod
  displayName: Deploy to Prod
  dependsOn: Approve_Prod
  condition: succeeded()
  jobs:
  - deployment: DeployToProd
    environment: 'Prod'
    pool: { name: Default }
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
          - template: deploy-iis-steps.yml
            parameters:
              siteName:  'dceg.co.za'
              appPool:   'dceg.co.za'
              host:      'dceg.co.za'
              physicalPath: 'C:\Sites\dceg.co.za'
