trigger:
- main

stages:
# ===== CI: Build & publish artifact =====
- stage: Build
  displayName: Build
  jobs:
  - job: BuildJob
    pool: { name: Default }
    variables:
      solution: '**/*.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'
    steps:
    - task: NuGetToolInstaller@1
    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        msbuildArgs: >-
          /p:DeployOnBuild=true
          /p:WebPublishMethod=Package
          /p:PackageAsSingleFile=true
          /p:SkipInvalidConfigurations=true
          /p:DesktopBuildPackageLocation="$(Build.ArtifactStagingDirectory)\WebApp.zip"
          /p:DeployIisAppPath="Default Web Site"
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: VSTest@2
      inputs:
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - publish: '$(Build.ArtifactStagingDirectory)'
      artifact: drop

# ===== CD: SIT =====
- stage: DeploySIT
  displayName: Deploy to SIT
  dependsOn: Build
  jobs:
  - deployment: DeployToDev
    environment: 'SIT'
    pool: { name: Default }
    strategy:
      runOnce:
        preDeploy:
          steps:
          - task: ManualValidation@0
            inputs:
              instructions: 'Approve to deploy to SIT'
              notifyUsers: 'anton@dceg.co.za'
              onTimeout: 'reject'
            timeoutInMinutes: 1440
        deploy:
          steps:
          - download: current
            artifact: drop
          - template: deploy-iis-steps.yml
            parameters:
              siteName:  sit.dceg.co.za
              appPool:   sit.dceg.co.za
              host:      sit.dceg.co.za
              physicalPath: C:\Sites\sit.dceg.co.za
              # optional:
              # packagePath: '$(Pipeline.Workspace)\drop\WebApp.zip'
              # enableHttps: true
              # certThumbprint: '0123456789ABCDEF0123456789ABCDEF01234567'

# ===== CD: UAT =====
- stage: DeployUAT
  displayName: Deploy to QA
  dependsOn: DeploySIT
  condition: succeeded()
  jobs:
  - deployment: DeployToUAT
    environment: 'UAT'
    pool: { name: Default }
    strategy:
      runOnce:
        preDeploy:
          steps:
          - task: ManualValidation@0
            inputs:
              instructions: 'Approve to deploy to UAT'
              notifyUsers: 'anton@dceg.co.za'
              onTimeout: 'reject'
            timeoutInMinutes: 1440
        deploy:
          steps:
          - download: current
            artifact: drop
          - template: deploy-iis-steps.yml
            parameters:
              siteName:  uat.dceg.co.za
              appPool:   uat.dceg.co.za
              host:      uat.dceg.co.za
              physicalPath: C:\Sites\uat.dceg.co.za

# ===== CD: Prod =====
- stage: DeployProd
  displayName: Deploy to Prod
  dependsOn: DeployUAT
  condition: succeeded()
  jobs:
  - deployment: DeployToProd
    environment: 'Prod'
    pool: { name: Default }
    strategy:
      runOnce:
        preDeploy:
          steps:
          - task: ManualValidation@0
            inputs:
              instructions: 'Approve to deploy to Prod'
              notifyUsers: 'anton@dceg.co.za'
              onTimeout: 'reject'
            timeoutInMinutes: 1440
        deploy:
          steps:
          - download: current
            artifact: drop
          - template: deploy-iis-steps.yml
            parameters:
              siteName:  dceg.co.za
              appPool:   dceg.co.za
              host:      dceg.co.za
              physicalPath: C:\Sites\dceg.co.za
