services:
  app:
    image: ghcr.io/anton-roos/lisa:latest
    container_name: lisa-app
    restart: always
    ports:
      - "8080:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    depends_on:
      - db
    networks:
      - lisa-network

  db:
    image: postgres:15
    container_name: lisa-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - lisa-network

volumes:
  postgres-data:

networks:
  lisa-network:
    driver: bridge
