// <auto-generated />
using System;
using Lisa.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lisa.Migrations
{
    [DbContext(typeof(LisaDbContext))]
    partial class LisaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lisa.Data.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SchoolId")
                        .HasColumnType("integer");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("Lisa.Data.Learner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LearnerCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RegisterClassId")
                        .HasColumnType("integer");

                    b.Property<int?>("RegisterClassId1")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LearnerCode");

                    b.HasIndex("RegisterClassId");

                    b.HasIndex("RegisterClassId1");

                    b.ToTable("Learners");
                });

            modelBuilder.Entity("Lisa.Data.LearnerParent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CellNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LearnerId")
                        .HasColumnType("integer");

                    b.Property<int?>("LearnerId1")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("LearnerId");

                    b.HasIndex("LearnerId1");

                    b.ToTable("LearnerParents");
                });

            modelBuilder.Entity("Lisa.Data.RegisterClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GradeId")
                        .HasColumnType("integer");

                    b.Property<int?>("GradeId1")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SchoolId")
                        .HasColumnType("integer");

                    b.Property<int>("SubjectCombinationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GradeId");

                    b.HasIndex("GradeId1");

                    b.HasIndex("SchoolId");

                    b.HasIndex("SubjectCombinationId");

                    b.ToTable("RegisterClasses");
                });

            modelBuilder.Entity("Lisa.Data.Result", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LearnerId")
                        .HasColumnType("integer");

                    b.Property<int?>("LearnerId1")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ResultDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Score")
                        .HasColumnType("numeric");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LearnerId");

                    b.HasIndex("LearnerId1");

                    b.HasIndex("Score");

                    b.HasIndex("SubjectId");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("Lisa.Data.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Schools");
                });

            modelBuilder.Entity("Lisa.Data.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SessionEndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("SessionStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.HasIndex("TeacherId", "SessionStartTime", "SessionEndTime")
                        .IsUnique();

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Lisa.Data.SessionSubject", b =>
                {
                    b.Property<int>("SessionId")
                        .HasColumnType("integer");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.Property<int?>("SessionId1")
                        .HasColumnType("integer");

                    b.HasKey("SessionId", "SubjectId", "TeacherId");

                    b.HasIndex("SessionId1");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("SessionId", "SubjectId");

                    b.ToTable("SessionSubjects");
                });

            modelBuilder.Entity("Lisa.Data.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("Lisa.Data.SubjectCombination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SubjectCombinations");
                });

            modelBuilder.Entity("Lisa.Data.SubjectCombinationSubject", b =>
                {
                    b.Property<int>("SubjectCombinationId")
                        .HasColumnType("integer");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.HasKey("SubjectCombinationId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("SubjectCombinationId", "SubjectId");

                    b.ToTable("SubjectCombinationSubjects");
                });

            modelBuilder.Entity("Lisa.Data.TeacherSubject", b =>
                {
                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.HasKey("TeacherId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("TeacherSubjects");
                });

            modelBuilder.Entity("Lisa.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LastName");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Lisa.Data.Administrator", b =>
                {
                    b.HasBaseType("Lisa.Data.User");

                    b.Property<int>("SchoolId")
                        .HasColumnType("integer");

                    b.HasIndex("SchoolId");

                    b.ToTable("Users", t =>
                        {
                            t.Property("SchoolId")
                                .HasColumnName("Administrator_SchoolId");
                        });

                    b.HasDiscriminator().HasValue("Administrator");
                });

            modelBuilder.Entity("Lisa.Data.Principal", b =>
                {
                    b.HasBaseType("Lisa.Data.User");

                    b.Property<int>("SchoolId")
                        .HasColumnType("integer");

                    b.HasIndex("SchoolId");

                    b.ToTable("Users", t =>
                        {
                            t.Property("SchoolId")
                                .HasColumnName("Principal_SchoolId");
                        });

                    b.HasDiscriminator().HasValue("Principal");
                });

            modelBuilder.Entity("Lisa.Data.SchoolManagement", b =>
                {
                    b.HasBaseType("Lisa.Data.User");

                    b.Property<int>("SchoolId")
                        .HasColumnType("integer");

                    b.HasIndex("SchoolId");

                    b.ToTable("Users", t =>
                        {
                            t.Property("SchoolId")
                                .HasColumnName("SchoolManagement_SchoolId");
                        });

                    b.HasDiscriminator().HasValue("SchoolManagement");
                });

            modelBuilder.Entity("Lisa.Data.SystemAdministrator", b =>
                {
                    b.HasBaseType("Lisa.Data.User");

                    b.Property<int>("SchoolId")
                        .HasColumnType("integer");

                    b.HasIndex("SchoolId");

                    b.ToTable("Users", t =>
                        {
                            t.Property("SchoolId")
                                .HasColumnName("SystemAdministrator_SchoolId");
                        });

                    b.HasDiscriminator().HasValue("SystemAdministrator");
                });

            modelBuilder.Entity("Lisa.Data.Teacher", b =>
                {
                    b.HasBaseType("Lisa.Data.User");

                    b.Property<int>("SchoolId")
                        .HasColumnType("integer");

                    b.HasIndex("SchoolId");

                    b.HasDiscriminator().HasValue("Teacher");
                });

            modelBuilder.Entity("Lisa.Data.Grade", b =>
                {
                    b.HasOne("Lisa.Data.School", "School")
                        .WithMany("Grades")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("Lisa.Data.Learner", b =>
                {
                    b.HasOne("Lisa.Data.RegisterClass", "RegisterClass")
                        .WithMany()
                        .HasForeignKey("RegisterClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lisa.Data.RegisterClass", null)
                        .WithMany("Learners")
                        .HasForeignKey("RegisterClassId1");

                    b.Navigation("RegisterClass");
                });

            modelBuilder.Entity("Lisa.Data.LearnerParent", b =>
                {
                    b.HasOne("Lisa.Data.Learner", "Learner")
                        .WithMany()
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lisa.Data.Learner", null)
                        .WithMany("LearnerParents")
                        .HasForeignKey("LearnerId1");

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("Lisa.Data.RegisterClass", b =>
                {
                    b.HasOne("Lisa.Data.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lisa.Data.Grade", null)
                        .WithMany("RegisterClasses")
                        .HasForeignKey("GradeId1");

                    b.HasOne("Lisa.Data.School", null)
                        .WithMany("RegisterClasses")
                        .HasForeignKey("SchoolId");

                    b.HasOne("Lisa.Data.SubjectCombination", "SubjectCombination")
                        .WithMany()
                        .HasForeignKey("SubjectCombinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grade");

                    b.Navigation("SubjectCombination");
                });

            modelBuilder.Entity("Lisa.Data.Result", b =>
                {
                    b.HasOne("Lisa.Data.Learner", "Learner")
                        .WithMany()
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lisa.Data.Learner", null)
                        .WithMany("Results")
                        .HasForeignKey("LearnerId1");

                    b.HasOne("Lisa.Data.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Learner");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Lisa.Data.Session", b =>
                {
                    b.HasOne("Lisa.Data.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Lisa.Data.SessionSubject", b =>
                {
                    b.HasOne("Lisa.Data.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lisa.Data.Session", null)
                        .WithMany("SessionSubjects")
                        .HasForeignKey("SessionId1");

                    b.HasOne("Lisa.Data.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lisa.Data.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Lisa.Data.SubjectCombinationSubject", b =>
                {
                    b.HasOne("Lisa.Data.SubjectCombination", "SubjectCombination")
                        .WithMany("SubjectCombinationSubjects")
                        .HasForeignKey("SubjectCombinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lisa.Data.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("SubjectCombination");
                });

            modelBuilder.Entity("Lisa.Data.TeacherSubject", b =>
                {
                    b.HasOne("Lisa.Data.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lisa.Data.Teacher", "Teacher")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Lisa.Data.Administrator", b =>
                {
                    b.HasOne("Lisa.Data.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("Lisa.Data.Principal", b =>
                {
                    b.HasOne("Lisa.Data.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("Lisa.Data.SchoolManagement", b =>
                {
                    b.HasOne("Lisa.Data.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("Lisa.Data.SystemAdministrator", b =>
                {
                    b.HasOne("Lisa.Data.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("Lisa.Data.Teacher", b =>
                {
                    b.HasOne("Lisa.Data.School", "School")
                        .WithMany("Teachers")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("Lisa.Data.Grade", b =>
                {
                    b.Navigation("RegisterClasses");
                });

            modelBuilder.Entity("Lisa.Data.Learner", b =>
                {
                    b.Navigation("LearnerParents");

                    b.Navigation("Results");
                });

            modelBuilder.Entity("Lisa.Data.RegisterClass", b =>
                {
                    b.Navigation("Learners");
                });

            modelBuilder.Entity("Lisa.Data.School", b =>
                {
                    b.Navigation("Grades");

                    b.Navigation("RegisterClasses");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("Lisa.Data.Session", b =>
                {
                    b.Navigation("SessionSubjects");
                });

            modelBuilder.Entity("Lisa.Data.SubjectCombination", b =>
                {
                    b.Navigation("SubjectCombinationSubjects");
                });

            modelBuilder.Entity("Lisa.Data.Teacher", b =>
                {
                    b.Navigation("TeacherSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
