name: Deploy to IIS

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        type: choice
        options: [qa, prod]

jobs:
  deploy:
    runs-on: self-hosted
    env:
      QA_PATH:   C:\Sites\dceg-learn
      PROD_PATH: C:\Sites\dceg-lis
      QA_POOL:   dceg-learn.co.za
      PROD_POOL: dceg-lis.co.za
      ROBOT_SAFE_XD: "logs uploads"

    steps:
      - uses: actions/checkout@v4

      - name: Select target paths (push=>QA, manual=>selected)
        shell: pwsh
        run: |
          if ("${{ github.event_name }}" -eq "push" -or "${{ github.event.inputs.environment }}" -eq "qa") {
            "DEPLOY_PATH=$env:QA_PATH"   | Out-File -FilePath $env:GITHUB_ENV -Append
            "APP_POOL=$env:QA_POOL"      | Out-File -FilePath $env:GITHUB_ENV -Append
          } else {
            "DEPLOY_PATH=$env:PROD_PATH" | Out-File -FilePath $env:GITHUB_ENV -Append
            "APP_POOL=$env:PROD_POOL"    | Out-File -FilePath $env:GITHUB_ENV -Append
          }
          "PUBLISH_DIR=$pwd\publish"     | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Publish
        run: dotnet publish --configuration Release --no-build --output "$env:PUBLISH_DIR"

      # Use app_offline to release locks (you can keep/skip the app pool stop if you want)
      - name: Take site offline
        shell: pwsh
        run: New-Item -ItemType File -Path "$env:DEPLOY_PATH\app_offline.htm" -Force | Out-Null

      # ---------- MISSING STEP ADDED ----------
      - name: Deploy (mirror, KEEP appsettings*.json)
        shell: pwsh
        run: |
          $src = $env:PUBLISH_DIR
          $dst = $env:DEPLOY_PATH
          # exclude server-side config; add 'web.config' if you also want to preserve it
          $cmd = "robocopy `"$src`" `"$dst`" /MIR /R:2 /W:2 /NFL /NDL /NP /XF appsettings.json appsettings.*.json"
          Write-Host $cmd
          cmd.exe /c $cmd
          if ($LASTEXITCODE -ge 8) { exit $LASTEXITCODE }
      # ---------------------------------------

      - name: Bring site online
        shell: pwsh
        run: Remove-Item "$env:DEPLOY_PATH\app_offline.htm" -Force -ErrorAction SilentlyContinue
